### ISSUE TITLE
EXPORT_HELPER_ID should start with a null byte when using Rollup

### ISSUE THREAD

**Issue by nielsvanvelzen** [sxzz/unplugin-vue#104]
### Describe the bug

The `EXPORT_HELPER_ID` doesn't start with a null byte at this moment. This causes issues with Rollup builds using `preserveModules`.

See also https://rollupjs.org/plugin-development/#conventions

### Reproduction

https://rollupjs.org/plugin-development/#conventions

### System Info

```Shell
Irrelevant
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
it will be a small change if you would like to send a PR.

**Comment by nielsvanvelzen** [comment]
Sure I can do that, but I'm not sure if that would break other build tools. AFAIK this is a Rollup specific convention.

**Comment by sxzz** [comment]
Hmmm I think it's ok, if we can pass the unit tests.

**Comment by nielsvanvelzen** [comment]
@sxzz would it be possible to publish a new version with this fix?

**Comment by sxzz** [comment]
Of course! Will do it today

**Comment by sxzz** [comment]
Released as v4.2.0
