### ISSUE TITLE
Styles are not applied in esbuild example

### ISSUE THREAD

**Issue by harveylee** [sxzz/unplugin-vue#109]
### Describe the bug

1. Build the esbuild example (i.e. `pnpm build` in `examples/esbuild`)
2. `dist/main.js` and `dist/main.css` are output
3. Load the preview (i.e. `pnpm preview` and point browser to `localhost:3000`)
4. Note that the `body` background color is _not_ aqua and the `h1` background color is _not_ yellow

Event though the styles are output, there's no reference to them injected into the `head` or otherwise?

### Reproduction

See description above

### System Info

```Shell
System:
    OS: Linux 5.15 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1250U
    Memory: 225.16 MB / 7.58 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - ~/.local/share/pnpm/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.165
    Chromium: 112.0.5615.138
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Fixed.
