### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by fgeierst** [sxzz/unplugin-vue#54]
> This project is inherited from [@vitejs/plugin-vue](https://github.com/vitejs/vite/tree/main/packages/plugin-vue)

Does this mean this project has the same codebase as @vitejs/plugin-vue, but repackaged to be compatible with ESBuild, Rollup and Webpack?

Is there a roadmap to a stable version?

**Comment by sxzz** [comment]
> Does this mean this project has the same codebase as @vitejs/plugin-vue, but repackaged to be compatible with ESBuild, Rollup and Webpack?

Yes.

> Is there a roadmap to a stable version?

It is now stable enough to be used in a production environment. I updated readme.
