### ISSUE TITLE
examples/webpack error

### ISSUE THREAD

**Issue by neostfox** [sxzz/unplugin-vue#83]
### Describe the bug

 Uncaught TypeError: _plugin_vue_export_helper__WEBPACK_IMPORTED_MODULE_1___default(...) is not a function
    at eval (App.vue:31:145)
    at ./src/App.vue (app.js:150:1)
    at __webpack_require__ (app.js:361:33)
    at fn (app.js:560:21)
    at eval (main.ts:3:66)
    at ./src/main.ts (app.js:29:1)
    at __webpack_require__ (app.js:361:33)
    at app.js:1433:37
    at app.js:1435:12

### Reproduction

this repository 

### System Info

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700H
    Memory: 3.16 GB / 15.73 GB
  Binaries:
    Node: 16.17.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.42)
    Internet Explorer: 11.0.22621.1
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/sxzz/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/sxzz/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sxzz** [comment]
Please provide a minimum reproduction.
It works normally in `examples/webpack` of the project.

**Comment by neostfox** [comment]
可能是windows 操作系统的原因，稍后我在 mac 上试试。辛苦。
